[package]
name = "kclvm-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde_json = "1.0"
serde_yaml = "0.8.7"
fancy-regex = "0.7.1"
indexmap = "1.0"
chrono = "0.4.19"
fslock = "0.2.1"
serde = { version = "1", features = ["derive"] }
kclvm-ast = {path = "../ast", version = "0.1.0"}
kclvm-error = {path = "../error", version = "0.1.0"}
kclvm-parser = {path = "../parser", version = "0.1.0"}
kclvm-sema = {path = "../sema", version = "0.1.0"}
kclvm-version = {path = "../version", version = "0.1.0"}
kclvm-runner = {path = "../runner", version = "0.1.0"}
kclvm-compiler = {path = "../compiler", version = "0.1.0"}
kclvm-config = {path = "../config", version = "0.1.0"}
kclvm-fileutils = {path = "../fileutils", version = "0.1.0"}

[dev-dependencies]
pretty_assertions = "1.2.1"